receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # мапим otel-поля в то, что ждёт syslog exporter
  transform/syslog:
    log_statements:
      - context: log
        statements:
          - set(attributes["message"], body)
          - set(attributes["priority"], severity_number)

  batch: {}

exporters:
  debug:
    verbosity: normal

  syslog/graylog:
    endpoint: graylog      # имя сервиса Graylog в docker-compose
    network: udp
    port: 1514             # Syslog UDP input в Graylog
    protocol: rfc5424
    timeout: 5s

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [transform/syslog, batch]
      exporters: [debug, syslog/graylog]
